from evoc.test.db.db_core import Test_db
from evoc.test.db.db_type import Test_db_type
from evoc.test.db.db_type_rel import Test_db_type_relationship
from evoc.test.db.db_taxon import Test_db_taxon
from evoc.test.db.db_gb import Test_db_gb
from evoc.test.db.db_cluster import Test_db_cluster
from evoc.test.db.db_gene import Test_db_gene
from evoc.test.db.db_cluster_gene import Test_db_cluster_gene
from evoc.test.db.db_compound import Test_db_molecule
from evoc.test.db.db_domain import Test_db_domain
